import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
        h-[100vh]
        flex flex-col items-center justify-center  
        bg-purple-900`}
      >
        <header className="
         w-[50vw] mb-1
         flex flex-row items-center justify-between 
         font-bold text-white"
        >
          <h1 className="text-4xl font-bold">Municípios</h1>
          <nav className="flex flex-row gap-1">
          <Link href="/" className="underline">Home</Link>
          <Link href="/municipalities" className="underline">Municípios</Link>
          </nav>
        </header>

        <main className="
          h-[70vh] w-[50vw] p-10 rounded-xl
          bg-white">
          
          {children}
          
        </main>
        
      </body>
    </html>
  );
}
